const languages = [
  {
    key: "EN",
    mainTitle: "Cutting parameters calculator",
    section1Title: "Milling/drilling",
    section2Title: "Threading/tapping",
    form1Legend: "Surface cutting speed",
    form1Input1Placeholder: "tool diameter",
    form1Input2Placeholder: "tool rotations",
    form1Input3Placeholder: "result",
    form1Input4Placeholder: "tool diameter",
    form2Legend: "Tool rotational speed",
    form3Legend: "Feedrate value",
    form4Legend: "Tapping feedrate",
    diameterName: "D",
    diameterUnit: " [mm]:",
    rotSpeedName: "n",
    rotSpeedSub: "rev",
    rotSpeedUnit: " [rev/min]:",
    cutSpeedName: "V",
    cutSpeedSub: "c",
    cutSpeedUnit: " [m/min]:",
  },
  {
    key: "PL",
    mainTitle: "Kalkulator obróbki skrawaniem",
    section1Title: "Frezowanie/wiercenie",
    section2Title: "Gwintowanie",
    form1Legend: "Liniowa prędkość skrawania",
    form1Input1Placeholder: "średnica narzędzia",
    form1Input2Placeholder: "obroty wrzeciona",
    form1Input3Placeholder: "wynik",
    form1Input4Placeholder: "średnica narzędzia",
    form2Legend: "Prędkość obrotowa narzędzia",
    form3Legend: "Wielkość posuwu liniowego",
    form4Legend: "Wielkość posuwu przy gwintowaniu",
    diameterName: "D",
    diameterUnit: " [mm]:",
    rotSpeedName: "n",
    rotSpeedSub: "obr",
    rotSpeedUnit: " [obr/min]:",
    cutSpeedName: "V",
    cutSpeedSub: "c",
    cutSpeedUnit: " [m/min]:",
  }
];

export default languages;